// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdhQVlSwiboI9q7l2MDmzP0h-K5XXHlE',
    appId: '1:582184259897:web:a0324c7f84fba58c0798e8',
    messagingSenderId: '582184259897',
    projectId: 'internshiptask-f1468',
    authDomain: 'internshiptask-f1468.firebaseapp.com',
    storageBucket: 'internshiptask-f1468.firebasestorage.app',
    measurementId: 'G-944NPJPV25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeS_CBLyDfO7uQNQPX-0yOZQ5haUTaLY0',
    appId: '1:582184259897:android:94dab69464a198920798e8',
    messagingSenderId: '582184259897',
    projectId: 'internshiptask-f1468',
    storageBucket: 'internshiptask-f1468.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdhQVlSwiboI9q7l2MDmzP0h-K5XXHlE',
    appId: '1:582184259897:web:98bd35f2384412db0798e8',
    messagingSenderId: '582184259897',
    projectId: 'internshiptask-f1468',
    authDomain: 'internshiptask-f1468.firebaseapp.com',
    storageBucket: 'internshiptask-f1468.firebasestorage.app',
    measurementId: 'G-SWTK9WFS28',
  );
}
